//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Risk_Mitigation_Portal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RiskMitigationEntities : DbContext
    {
        public RiskMitigationEntities()
            : base("name=RiskMitigationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RiskMitigation> RiskMitigations { get; set; }
        public virtual DbSet<RmtFileUpload> RmtFileUploads { get; set; }
    
        public virtual int dbo_spTracker_AddorEdit(Nullable<int> iD, string lcNumber, string name, string country, string status)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var lcNumberParameter = lcNumber != null ?
                new ObjectParameter("LcNumber", lcNumber) :
                new ObjectParameter("LcNumber", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("Country", country) :
                new ObjectParameter("Country", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_spTracker_AddorEdit", iDParameter, lcNumberParameter, nameParameter, countryParameter, statusParameter);
        }
    
        public virtual int dbo_spTracker_DeleteById(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dbo_spTracker_DeleteById", iDParameter);
        }
    
        public virtual ObjectResult<dbo_spTracker_Search_Result> dbo_spTracker_Search(string searchText)
        {
            var searchTextParameter = searchText != null ?
                new ObjectParameter("SearchText", searchText) :
                new ObjectParameter("SearchText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dbo_spTracker_Search_Result>("dbo_spTracker_Search", searchTextParameter);
        }
    
        public virtual ObjectResult<dbo_spTracker_ShowAll_Result> dbo_spTracker_ShowAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dbo_spTracker_ShowAll_Result>("dbo_spTracker_ShowAll");
        }
    }
}
